<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All' => 'Все',
    'All orders' => 'Все заявки',
    'Auto' => 'Авто',
    'Canceled' => 'Отменен',
    'Completed' => 'Выполнен',
    'Created At' => 'Создан',
    'Download Results' => 'Скачать',
    'Fail' => 'Ошибка',
    'First Name' => 'Имя',
    'ID' => 'ID',
    'In progress' => 'В процессе',
    'Last Name' => 'Фамилия',
    'Link' => 'Ссылка',
    'Manual' => 'Ручной',
    'Mode' => 'Режим',
    'Name' => 'Название',
    'Order ID' => '№ Заявки',
    'Orders' => 'Заявки',
    'Pending' => 'Рассматриваемый',
    'Quantity' => 'Кол-во',
    'Search orders' => 'Поиск',
    'Service' => 'Сервис',
    'Service ID' => '№ Сервиса',
    'Status' => 'Статус',
    'The requested page does not exist.' => 'Такой страницы не существует',
    'User' => 'Пользователь',
    'User ID' => '№ Пользователя',
    'Username' => 'Ф. И. О.',
    '{begin} to {end} of {totalCount}' => 'с {begin} по {end} из {totalCount}',
    'Service Name' => 'Название сервиса',
];
