<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'csv.created_at' => 'Создано',
    'csv.link' => 'Ссылка',
    'csv.mode' => 'Режим',
    'csv.service_name' => 'Сервис',
    'csv.quantity' => 'Кол-во',
    'csv.status' => 'Статус',
    'csv.username' => 'Ф. И. О.',
    'mainmenu.orders' => 'Заявки',
    'models.orders.label.created_at' => 'Создано',
    'models.orders.label.dropdown.auto' => 'Авто',
    'models.orders.label.dropdown.manual' => 'Ручной',
    'models.orders.label.id' => '№',
    'models.orders.label.link' => 'Ссылка',
    'models.orders.label.mode' => 'Режим',
    'models.orders.label.quantity' => 'Количество',
    'models.orders.label.service_id' => 'Сервис',
    'models.orders.label.status' => 'Статус',
    'models.orders.label.user_id' => '№ Пользователя',
    'models.orders.status.label.canceled' => 'Отменен',
    'models.orders.status.label.completed' => 'Выполнен',
    'models.orders.status.label.fail' => 'Ошибка',
    'models.orders.status.label.in_progress' => 'В процессе',
    'models.orders.status.label.pending' => 'Предстоящий',
    'models.search.orderssearch.all' => 'Все',
    'models.search.orderssearch.label.all' => 'Все',
    'models.search.orderssearch.label.mode' => 'Режим',
    'models.search.orderssearch.label.service' => 'Сервис',
    'models.search.orderssearch.mode.all' => 'Все',
    'models.services.label.id' => '№',
    'models.services.label.name' => 'Название',
    'models.users.label.firstname' => 'Имя',
    'models.users.label.id' => '№',
    'models.users.label.lastname' => 'Фамилия',
    'modules.orders.label.link' => 'Ссылка',
    'modules.orders.label.order_id' => '№',
    'modules.orders.label.username' => 'Ф. И. О.',
    'views.orders._search.download' => 'Скачать результаты',
    'views.orders._search.search' => 'Искать',
    'views.orders.index.label.link' => 'Ссылка',
    'views.orders.index.label.quantity' => 'Количество',
    'views.orders.index.label.status' => 'Статус',
    'views.orders.index.label.user' => 'Пользователь',
    '{begin} to {end} of {totalCount}' => 'c {begin} по {end} из {totalCount}',
    'orders.widgets.status.label.all' => 'Все',
];
