<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'csv.created_at' => 'Created at',
    'csv.link' => 'Link',
    'csv.mode' => 'Mode',
    'csv.service_name' => 'Service name',
    'csv.quantity' => 'Quantity',
    'csv.status' => 'Status',
    'csv.username' => 'Username',
    'mainmenu.orders' => 'Orders',
    'models.orders.label.created_at' => 'Created at',
    'models.orders.label.dropdown.auto' => 'Auto',
    'models.orders.label.dropdown.manual' => 'Manual',
    'models.orders.label.id' => 'Id',
    'models.orders.label.link' => 'Link',
    'models.orders.label.mode' => 'Mode',
    'models.orders.label.quantity' => 'Quantity',
    'models.orders.label.service_id' => 'Service Id',
    'models.orders.label.status' => 'Status',
    'models.orders.label.user_id' => 'User Id',
    'models.orders.status.label.canceled' => 'Canceled',
    'models.orders.status.label.completed' => 'Completed',
    'models.orders.status.label.fail' => 'Fail',
    'models.orders.status.label.in_progress' => 'In progress',
    'models.orders.status.label.pending' => 'Pending',
    'models.search.orderssearch.all' => 'All',
    'models.search.orderssearch.label.all' => 'All',
    'models.search.orderssearch.label.mode' => 'Mode',
    'models.search.orderssearch.label.service' => 'Service',
    'models.search.orderssearch.mode.all' => 'All',
    'models.services.label.id' => 'Service Id',
    'models.services.label.name' => 'Service name',
    'models.users.label.firstname' => 'First name',
    'models.users.label.id' => 'Id',
    'models.users.label.lastname' => 'Last name',
    'modules.orders.label.link' => 'Link',
    'modules.orders.label.order_id' => 'Order Id',
    'modules.orders.label.username' => 'Username',
    'views.orders._search.download' => 'Download results',
    'views.orders._search.search' => 'Search',
    'views.orders.index.label.link' => 'Link',
    'views.orders.index.label.quantity' => 'Quantity',
    'views.orders.index.label.status' => 'Status',
    'views.orders.index.label.user' => 'User',
    '{begin} to {end} of {totalCount}' => '{begin} to {end} of {totalCount}',
    'orders.widgets.status.label.all' => 'All',
];
